apiVersion: apps/v1
kind: Deployment
metadata:
  name: tinybench
  namespace: tinybench
  labels:
    app.kubernetes.io/name: tinybench
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge: 1
       maxUnavailable: 1
  selector:
    matchLabels:
      app: tinybench
  template:
    metadata:
      labels:
        app: tinybench
        version: beta-2202-19-21
        deploy: deploy-22-02-19-21-51-25
    spec:
      containers:
        - name: app
          image: ghcr.io/bartr/tinybench:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          args:
          - -u
          - /heartbeat

---
apiVersion: v1
kind: Service
metadata:
  name: tinybench
  namespace: tinybench
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: tinybench
    
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: tinybench-https
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`central-ks-kc-105.cseretail.com`) && PathPrefix(`/heartbeat/`)
      kind: Rule
      services:
        - name: tinybench
          namespace: tinybench
          kind: Service
          port: 8080
  tls:
    secretName: ssl-cert
