apiVersion: v1
kind: Service
spec:
  type: NodePort
  selector:
    app: testapp
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080

metadata:
  namespace: testapp
  labels:
    app: testapp
  name: testapp

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: testapp-https
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`west-wa-spokane-101.cseretail.com`)
      kind: Rule
      services:
        - name: testapp
          namespace: testapp
          kind: Service
          port: 8080
  tls:
    secretName: ssl-cert
