apiVersion: apps/v1
kind: Deployment
metadata:
  name: testwebapitemplate
  namespace: testwebapitemplate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testwebapitemplate
  template:
    metadata:
      labels:
        app: testwebapitemplate
        buildTag: build-0.0.1-0406-0547
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
    spec:
      containers:
        - name: app
          image: ghcr.io/retaildevcrews/testwebapitemplate:beta
          imagePullPolicy: Always

          args:
          - --zone
          - east-ny-nyc
          - --region
          - east

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
