apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-order-accuracy
  namespace: ai-order-accuracy
  labels:
    app.kubernetes.io/name: ai-order-accuracy
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge: 1
       maxUnavailable: 1
  selector:
    matchLabels:
      app: ai-order-accuracy
  template:
    metadata:
      labels:
        app: ai-order-accuracy
    spec:
      containers:
        - name: app
          image: ghcr.io/cse-labs/ngsa-app:latest
          imagePullPolicy: Always
          args: 
          - --in-memory
          - --prometheus
          - --zone
          - central-tx-houston
          - --region
          - central
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 512Mi

---
apiVersion: v1
kind: Service
metadata:
  name: ai-order-accuracy
  namespace: ai-order-accuracy
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: ai-order-accuracy
    
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ai-order-accuracy-https
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`central-tx-houston-101.cseretail.com`)
      kind: Rule
      services:
        - name: ai-order-accuracy
          namespace: ai-order-accuracy
          kind: Service
          port: 8080
  tls:
    secretName: ssl-cert
