apiVersion: apps/v1
kind: Deployment
metadata:
  name: pilotapp
  namespace: pilotapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pilotapp
  template:
    metadata:
      labels:
        app: pilotapp
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
    spec:
      containers:
        - name: app
          image: ghcr.io/retaildevcrews/pilotapp:latest
          imagePullPolicy: Always

          args:
          - --zone
          - central-il-chi
          - --region
          - central

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
